# Generated by Django 5.0.7 on 2024-07-10 09:05

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublishableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('state', django_fsm.FSMField(choices=[('draft', 'draft'), ('approved', 'approved'), ('published', 'published'), ('expired', 'expired'), ('deleted', 'deleted')], default='draft', max_length=50, protected=True, verbose_name='Publication State')),
                ('display_from', models.DateTimeField(blank=True, null=True)),
                ('display_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
